# Generated by Django 4.1.1 on 2022-09-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('postTitle', models.CharField(max_length=200)),
                ('postBulk', models.CharField(max_length=500)),
                ('postPic', models.CharField(max_length=200)),
            ],
        ),
    ]
